title: Financial Analysis of a Fictitious Company
description: Portfolio site with financial data charts and reports.
baseurl: "/financial-analysis-of-a-fictitious-company"
url: "https://marcin-charzynski.github.io"
plugins:
  - jekyll-remote-theme
remote_theme: Marcin-Charzynski/marcin-charzynski.github.io
markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    line_numbers: true